DOMAIN = "home_maintenance_manager"
PLATFORMS = ["sensor", "binary_sensor", "button"]
STORAGE_VERSION = 2
STORAGE_KEY = DOMAIN
LEGACY_STORAGE_VERSION = 1
LEGACY_STORAGE_KEY = f"{DOMAIN}.tasks"
CONF_TASKS = "tasks"
DEFAULT_WARNING_PERCENT = 0.8
DEFAULT_NOTIFICATION_MODE = "automation_only"
SERVICE_MARK_COMPLETE = "mark_complete"
SERVICE_SNOOZE = "snooze"
SERVICE_ADD_LOG = "add_log"
SERVICE_RESET_RUNTIME = "reset_runtime"
SERVICE_UPSERT_TASK = "upsert_task"
SERVICE_DELETE_TASK = "delete_task"
EVENT_ACTIVITY = f"{DOMAIN}_activity"
EVENT_COMPLETION = f"{DOMAIN}_completion"
EVENT_NFC_SCAN = f"{DOMAIN}_nfc_scan"
